dist: trusty

branches:
  only:
  - master
  - dev
  - /feature*/

stages:
- name: build feature
  if: branch =~ feature*
- name: build dev docker image
  if: branch = dev
- name: build prod docker image
  if: branch = master
  
jobs:
  include:
    - stage: build feature
      script: 
      - sed -i 's)$sonarlogin)'"$SONAR_TOKEN"')g' ./Dockerfile
      - sed -i 's)$cstring)'"$CONNECTION_STRING_DEV"')g' ./listelab-contrato/App.config.example
      - rm -f ./listelab-contrato/App.config
      - mv ./listelab-contrato/App.config.example ./listelab-contrato/App.config
      - docker build --no-cache -t $DOCKER_USERNAME/listelab-server:dev .
    - stage: build dev docker image
      script:
      - sed -i 's)$sonarlogin)'"$SONAR_TOKEN"')g' ./Dockerfile
      - sed -i 's)$cstring)'"$CONNECTION_STRING_DEV"')g' ./listelab-contrato/App.config.example
      - rm -f ./listelab-contrato/App.config
      - mv ./listelab-contrato/App.config.example ./listelab-contrato/App.config
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build --no-cache -t $DOCKER_USERNAME/listelab-server:dev .
      - docker images
      - docker tag $DOCKER_USERNAME/listelab-server:dev $DOCKER_USERNAME/listelab-server:dev
      - docker push $DOCKER_USERNAME/listelab-server:dev
    - stage: build prod docker image
      script:
      - sed -i 's)$sonarlogin)'"$SONAR_TOKEN"')g' ./Dockerfile
      - sed -i 's)$cstring)'"$CONNECTION_STRING_PROD"')g' ./listelab-contrato/App.config.example
      - rm -f ./listelab-contrato/App.config
      - mv ./listelab-contrato/App.config.example ./listelab-contrato/App.config
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build --no-cache -t $DOCKER_USERNAME/listelab-server .
      - docker images
      - docker tag $DOCKER_USERNAME/listelab-server $DOCKER_USERNAME/listelab-server
      - docker push $DOCKER_USERNAME/listelab-server

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
